const KAHOOT={"0301":"https://kahoot.it/solo?quizId=b6d26fb9-efba-4ecb-863d-87d01c94573e","0302":"https://kahoot.it/solo?quizId=eae47461-984c-43d5-8bfe-ddf24be8afee","0303":"","0304":"","0305":"","0306":"","0307":"","0308":"","0401":"","0402":"","0403":"","0404":"","0405":"","0406":"","0407":"","0501":"","0502":"","0503":"","0504":"","0505":"","0601":"","0602":"","0603":"","UTS_GASAL_03":"https://kahoot.it/solo?quizId=18c0fab3-ea5b-451f-97ed-6aab996cdd79","UAS_GASAL_03":"","UTS_GENAP_03":"","UAS_GENAP_03":"","UTS_GASAL_04":"","UAS_GASAL_04":"","UTS_GENAP_04":"","UAS_GENAP_04":"","UTS_GASAL_05":"","UAS_GASAL_05":"","UTS_GENAP_05":"","UAS_GENAP_05":"","UTS_GASAL_06":"","UAS_GASAL_06":"","UTS_GENAP_UAS_GENAP_06":""};
const DATA={3:["Kelas III","📗",[[1,"SEMESTER 1",[["I","Surah Al-Fatihah","0301"],["II","Surah An-Nas","0302"],["III","Surah Al-Falaq","0303"],["IV","Surah Al-Ikhlas","0304"]],[["UTS Gasal","UTS_GASAL_03"],["UAS Gasal","UAS_GASAL_03"]]],[2,"SEMESTER 2",[["V","Surah Al-Lahab","0305"],["VI","Surah An-Nashr","0306"],["VII","Surah Al-Kafirun","0307"],["VIII","Surah Al-Kautsar","0308"]],[["UTS Genap","UTS_GENAP_03"],["UAS Genap","UAS_GENAP_03"]]]]],4:["Kelas IV","📘",[[1,"SEMESTER 1",[["I","Surah Al-Ma'un","0401"],["II","Surah Quraisy","0402"],["III","Surah Al-Fil","0403"],["IV","Surah Al-Humazah","0404"]],[["UTS Gasal","UTS_GASAL_04"],["UAS Gasal","UAS_GASAL_04"]]],[2,"SEMESTER 2",[["V","Surah Al-'Asr","0405"],["VI","Surah At-Takatsur","0406"],["VII","Surah Al-Qari'ah","0407"]],[["UTS Genap","UTS_GENAP_04"],["UAS Genap","UAS_GENAP_04"]]]]],5:["Kelas V","📙",[[1,"SEMESTER 1",[["I","Surah Al-'Adiyat","0501"],["II","Surah Az-Zalzalah","0502"],["III","Surah Al-Bayyinah","0503"]],[["UTS Gasal","UTS_GASAL_05"],["UAS Gasal","UAS_GASAL_05"]]],[2,"SEMESTER 2",[["IV","Surah Al-Qadr","0504"],["V","Surah Al-'Alaq","0505"]],[["UTS Genap","UTS_GENAP_05"],["UAS Genap","UAS_GENAP_05"]]]]],6:["Kelas VI","📕",[[1,"SEMESTER 1",[["I","Surah At-Tin","0601"],["II","Surah Al-Insyirah","0602"]],[["UTS Gasal","UTS_GASAL_06"],["UAS Gasal","UAS_GASAL_06"]]],[2,"SEMESTER 2",[["III","Surah Adh-Dhuha","0603"]],[["UTS Genap / UAS Genap","UTS_GENAP_UAS_GENAP_06"]]]]]};
const $=id=>document.getElementById(id),home=$("home"),content=$("content"),viewer=$("viewer");let last=null;
function path(c,t,n){return`data/kelas${c}/${t}MQ${n}.${t==="Ringkas"?"pdf":"jpg"}`}
function kahoot(u){return u?`<a class="action kahoot" href="${u}" target="_blank">🎮 Latihan Kahoot</a>`:`<span class="action kahoot disabled">🎮 Latihan Kahoot<br>Belum tersedia</span>`}
function doc(p,label,title,sub,type){return`<button class="action" onclick='openDoc(${JSON.stringify(p)},${JSON.stringify(title)},${JSON.stringify(sub)},${JSON.stringify(type)})'>${label}</button>`}
function show(c){last=c;const d=DATA[c];home.classList.add("hide");viewer.classList.add("hide");content.classList.remove("hide");$("head").innerHTML=`<div class="title"><h2>${d[1]} ${d[0]}</h2><p>Materi • Kahoot • Tugas • Evaluasi</p></div>`;$("semesters").innerHTML=d[2].map(s=>`<section class="semester"><h3>📖 ${s[1]}</h3>${s[2].map(b=>`<article class="bab"><div class="babhead"><h4>Bab ${b[0]}</h4><p>${b[1]}</p></div><div class="actions">${doc(path(c,"Ringkas",b[2]),"📄 Rangkuman Materi","📄 Rangkuman Materi • Bab "+b[0],b[1],"pdf")}${kahoot(KAHOOT[b[2]])}${doc(path(c,"Tugas",b[2]),"📝 Nilai Tugas","📝 Nilai Tugas • Bab "+b[0],b[1],"image")}${doc(path(c,"UH",b[2]),"📊 Nilai UH","📊 Nilai Ulangan Harian • Bab "+b[0],b[1],"image")}</div></article>`).join("")}<h3>🏆 Evaluasi</h3><div class="eval">${s[3].map(e=>KAHOOT[e[1]]?`<a href="${KAHOOT[e[1]]}" target="_blank">🎯 ${e[0]}</a>`:`<span class="eval disabled">🎯 ${e[0]}<br>Belum tersedia</span>`).join("")}</div></section>`).join("");scrollTo(0,0)}
function openDoc(p,t,s,type){home.classList.add("hide");content.classList.add("hide");viewer.classList.remove("hide");$("vtitle").textContent=t;$("vsub").textContent=s;$("newtab").href=p;$("doc").innerHTML=type==="pdf"?`<iframe src="${p}" title="${t}"></iframe>`:`<img src="${p}" alt="${t}" onerror="this.outerHTML='<p style="color:white;text-align:center">File belum tersedia. Periksa nama file dan folder.</p>'">`;scrollTo(0,0)}
$("classes").innerHTML=Object.entries(DATA).map(([n,d])=>`<button class="class" onclick="show(${n})"><b>${d[1]}</b><strong>${d[0]}</strong><small>Materi & Evaluasi</small></button>`).join("");
$("back").onclick=()=>{content.classList.add("hide");home.classList.remove("hide");last=null;scrollTo(0,0)};$("vback").onclick=()=>{viewer.classList.add("hide");if(last)content.classList.remove("hide");else home.classList.remove("hide");scrollTo(0,0)};
